### PR TITLE
Add Windows to CI matrix

### PR DESCRIPTION
**Pull request by ybiquitous**
This pull request adds Windows OS to the CI matrix. And, for compatibility between OS, this fixes quotes in `npm run` scripts.

### CODE REVIEW

**Comment by ybiquitous** [comment]
I find the test on Windows fails:

```
Error: ENOENT: no such file or directory, open 'D:\D:\a\css-functions-list\css-functions-list\index.json'
```

https://github.com/ybiquitous/css-functions-list/runs/5171276724?check_suite_focus=true#step:7:17

**Comment by ybiquitous** [comment]
For example, what if exporting a function that returns an `URL` object like this?

```js
export const locationURL = () => {
	return new URL('index.json', import.meta.url);
}

const location = locationURL().pathname;

export default location;
```

[`fs.readFile()`](https://nodejs.org/api/fs.html#fsreadfilepath-options-callback) supports also the `URL` type as an argument.

`URL` never causes a pathname problem on OS file systems.

**Comment by niksy** [comment]
Thanks for the PR!

Initial implementation was following [simplest use case on how to resolve `__filename` and `__dirname`](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c#what-do-i-use-instead-of-__dirname-and-__filename), but I guess this isn’t bulletproof for Windows so I switched to additional check with [`fileURLToPath`](https://nodejs.org/api/url.html#urlfileurltopathurl). That works now on both Linux and Windows so I will use that.

**Comment by ybiquitous** [comment]
@niksy `fileURLToPath` is what we were looking for. Thank you! 👍🏼

**Pull request merged**
